version: 2

sources:
  - name: demo
    database: demo
    schema: demo_schema
    tables:
      - name: bike
      - name: weather

  - name: btc
    database: btc
    schema: btc_schema
    tables:
      - name: btc